# Generated by Django 2.1.4 on 2019-02-08 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20190208_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='Average',
        ),
        migrations.RemoveField(
            model_name='architect',
            name='Average',
        ),
        migrations.RemoveField(
            model_name='civil_engr',
            name='Average',
        ),
        migrations.RemoveField(
            model_name='electronics_engr',
            name='Average',
        ),
        migrations.RemoveField(
            model_name='mechanical_engr',
            name='Average',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='Average',
        ),
        migrations.AddField(
            model_name='applicant',
            name='Class_Demo',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Class demo '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architect',
            name='Class_Demo',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Class demo '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='civil_engr',
            name='Class_Demo',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Class demo '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronics_engr',
            name='Class_Demo',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Class demo '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanical_engr',
            name='Class_Demo',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Class demo '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='Class_Demo',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Class demo '),
            preserve_default=False,
        ),
    ]
