# Generated by Django 2.1.4 on 2019-02-08 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20190208_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='Evaluator',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='Interviewer',
        ),
        migrations.RemoveField(
            model_name='architect',
            name='Evaluator',
        ),
        migrations.RemoveField(
            model_name='architect',
            name='Interviewer',
        ),
        migrations.RemoveField(
            model_name='civil_engr',
            name='Evaluator',
        ),
        migrations.RemoveField(
            model_name='civil_engr',
            name='Interviewer',
        ),
        migrations.RemoveField(
            model_name='electronics_engr',
            name='Evaluator',
        ),
        migrations.RemoveField(
            model_name='electronics_engr',
            name='Interviewer',
        ),
        migrations.RemoveField(
            model_name='mechanical_engr',
            name='Evaluator',
        ),
        migrations.RemoveField(
            model_name='mechanical_engr',
            name='Interviewer',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='Evaluator',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='Interviewer',
        ),
        migrations.AddField(
            model_name='applicant',
            name='Practical_Exam',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Practical exam '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architect',
            name='Practical_Exam',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Practical exam '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='civil_engr',
            name='Practical_Exam',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Practical exam '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronics_engr',
            name='Practical_Exam',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Practical exam '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanical_engr',
            name='Practical_Exam',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Practical exam '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='Practical_Exam',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Practical exam '),
            preserve_default=False,
        ),
    ]
