# Generated by Django 2.1.4 on 2019-02-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20190209_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civil_engr',
            old_name='Eligibilty',
            new_name='Eligibility',
        ),
        migrations.RenameField(
            model_name='electronics_engr',
            old_name='Eligibilty',
            new_name='Eligibility',
        ),
        migrations.RenameField(
            model_name='mechanical_engr',
            old_name='Eligibilty',
            new_name='Eligibility',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='Eligibilty',
            new_name='Eligibility',
        ),
        migrations.RemoveField(
            model_name='architect',
            name='Eligibilty',
        ),
        migrations.AddField(
            model_name='applicant',
            name='Eligibility',
            field=models.CharField(default=0, editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architect',
            name='Eligibility',
            field=models.CharField(choices=[('none', 'None'), ('yes', 'License for ARC')], default=0, max_length=100, verbose_name='Eligibility'),
            preserve_default=False,
        ),
    ]
