# Generated by Django 2.1.4 on 2019-02-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20190209_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='architect',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='civil_engr',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='electronics_engr',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='mechanical_engr',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number '),
        ),
    ]
