# Generated by Django 2.1.4 on 2019-02-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20190209_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Civil_Status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('spouse', 'Spouse')], default=' ', max_length=7, verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='Civil_Status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('spouse', 'Spouse')], default=' ', max_length=7, verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='architect',
            name='Eligibility',
            field=models.CharField(choices=[('none', 'None'), ('yes', 'License for Architect')], default=' ', max_length=100, verbose_name='Eligibility'),
        ),
        migrations.AlterField(
            model_name='civil_engr',
            name='Civil_Status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('spouse', 'Spouse')], default=' ', max_length=7, verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='civil_engr',
            name='Eligibility',
            field=models.CharField(choices=[('none', 'None'), ('yes', 'License for CE')], default=' ', max_length=100, verbose_name='Eligibility'),
        ),
        migrations.AlterField(
            model_name='electronics_engr',
            name='Civil_Status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('spouse', 'Spouse')], default=' ', max_length=7, verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='electronics_engr',
            name='Eligibility',
            field=models.CharField(choices=[('none', 'None'), ('yes', 'License for EE')], default=' ', max_length=100, verbose_name='Eligibility'),
        ),
        migrations.AlterField(
            model_name='mechanical_engr',
            name='Civil_Status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('spouse', 'Spouse')], default=' ', max_length=7, verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='mechanical_engr',
            name='Eligibility',
            field=models.CharField(choices=[('none', 'None'), ('yes', 'License for ME')], default=' ', max_length=100, verbose_name='Eligibility'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='Civil_Status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('spouse', 'Spouse')], default=' ', max_length=7, verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='Eligibility',
            field=models.CharField(choices=[('none', 'None'), ('yes', 'License for Nurse')], default=' ', max_length=100, verbose_name='Eligibility'),
        ),
    ]
