# Generated by Django 2.1.4 on 2019-02-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_remove_applicant_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='time',
            field=models.CharField(default=0, editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
