# Generated by Django 2.1.4 on 2019-02-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_applicant_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='time',
        ),
        migrations.AddField(
            model_name='applicant',
            name='License',
            field=models.BooleanField(default=0, verbose_name='License for teaching '),
            preserve_default=False,
        ),
    ]
