# Generated by Django 2.1.4 on 2019-02-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20190228_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='License',
            field=models.BooleanField(default=0, verbose_name='License for teaching '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='civil_engr',
            name='License',
            field=models.BooleanField(default=0, verbose_name='License for teaching '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronics_engr',
            name='License',
            field=models.BooleanField(default=0, verbose_name='License for teaching '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanical_engr',
            name='License',
            field=models.BooleanField(default=0, verbose_name='License for teaching '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='License',
            field=models.BooleanField(default=0, verbose_name='License for teaching '),
            preserve_default=False,
        ),
    ]
